/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package employee.payroll;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.*;
import net.proteanit.sql.DbUtils;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableModel;

/**
 *
 * @author chayatan
 */
public class AccountHeads extends javax.swing.JFrame {

    Connection conn = null;
    ResultSet rs = null;
    PreparedStatement pst = null;
    String accID = "";
    /**
     * Creates new form AccountHeads
     */

    public AccountHeads() {
        initComponents();
        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width / 2 - getWidth() / 2, size.height / 2 - getHeight() / 2);

        conn = db.java_db();
        updateTable();
    }

    public void updateTable() {

        try {

            String sql = "select Account_Head, Category, Debit, Credit from acc_heads";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            table_acchead.setModel(DbUtils.resultSetToTableModel(rs));

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dialog_AccHead = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_accName = new javax.swing.JTextField();
        txt_underTheGroup = new javax.swing.JTextField();
        txt_debitBalance = new javax.swing.JTextField();
        txt_creditBalance = new javax.swing.JTextField();
        dialog_category = new javax.swing.JComboBox<>();
        dialog_save = new javax.swing.JButton();
        dialog_exit = new javax.swing.JButton();
        dialog_modify = new javax.swing.JButton();
        jFrame1 = new javax.swing.JFrame();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_acchead = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        create_acc_head = new javax.swing.JMenuItem();
        exit_item = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        dialog_AccHead.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                dialog_AccHeadKeyPressed(evt);
            }
        });

        jLabel1.setText("Account Heads");

        jLabel2.setText("Account Name : ");

        jLabel3.setText("Category :");

        jLabel4.setText("Under the Group :");

        jLabel5.setText("Debit Balance :");

        jLabel6.setText("Credit Balance :");

        txt_accName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_accNameActionPerformed(evt);
            }
        });
        txt_accName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_accNameKeyPressed(evt);
            }
        });

        dialog_category.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Balance sheet A/c", "Capital A/c", "Debitors/Creditors A/c", "Loans & Advances A/c", "Profit & Loss A/c", "Trading A/c" }));
        dialog_category.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dialog_categoryActionPerformed(evt);
            }
        });

        dialog_save.setText("Create");
        dialog_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dialog_saveActionPerformed(evt);
            }
        });

        dialog_exit.setText("Exit");
        dialog_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dialog_exitActionPerformed(evt);
            }
        });

        dialog_modify.setText("Modify");
        dialog_modify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dialog_modifyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dialog_AccHeadLayout = new javax.swing.GroupLayout(dialog_AccHead.getContentPane());
        dialog_AccHead.getContentPane().setLayout(dialog_AccHeadLayout);
        dialog_AccHeadLayout.setHorizontalGroup(
            dialog_AccHeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialog_AccHeadLayout.createSequentialGroup()
                .addGroup(dialog_AccHeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dialog_AccHeadLayout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addComponent(jLabel1))
                    .addGroup(dialog_AccHeadLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(dialog_AccHeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(58, 58, 58)
                        .addGroup(dialog_AccHeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(dialog_category, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txt_accName)
                            .addComponent(txt_underTheGroup)
                            .addComponent(txt_debitBalance)
                            .addComponent(txt_creditBalance)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dialog_AccHeadLayout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(dialog_modify)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dialog_save)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dialog_exit)))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        dialog_AccHeadLayout.setVerticalGroup(
            dialog_AccHeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialog_AccHeadLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addGroup(dialog_AccHeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_accName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(dialog_AccHeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(dialog_category, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(dialog_AccHeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txt_underTheGroup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(dialog_AccHeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txt_debitBalance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(dialog_AccHeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txt_creditBalance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(dialog_AccHeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dialog_save)
                    .addComponent(dialog_exit)
                    .addComponent(dialog_modify)))
        );

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(700, 500));

        table_acchead.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Account Head", "Category", "Debit", "Credit"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TableCellRenderer rendererFromHeader = table_acchead.getTableHeader().getDefaultRenderer();
        JLabel headerLabel = (JLabel) rendererFromHeader;
        headerLabel.setHorizontalAlignment(JLabel.CENTER);
        table_acchead.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_accheadMouseClicked(evt);
            }
        });
        table_acchead.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                table_accheadKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(table_acchead);

        jLabel7.setText("F2=Create   F3=Delete    ENTER=Modify    ESC=Exit");

        jMenu1.setText("File");

        create_acc_head.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, 0));
        create_acc_head.setText("Create ");
        create_acc_head.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                create_acc_headActionPerformed(evt);
            }
        });
        jMenu1.add(create_acc_head);

        exit_item.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE, 0));
        exit_item.setText("Exit");
        exit_item.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exit_itemActionPerformed(evt);
            }
        });
        jMenu1.add(exit_item);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(158, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(150, 150, 150))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dialog_categoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dialog_categoryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dialog_categoryActionPerformed

    private void txt_accNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_accNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_accNameActionPerformed

    private void dialog_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dialog_saveActionPerformed
        // TODO add your handling code here:
        String sql = "insert into acc_heads (Account_Head, Category, Debit, Credit) values (?, ?, ?, ?)";
        try {

            pst = conn.prepareStatement(sql);
            pst.setString(1, txt_accName.getText());
            pst.setString(2, dialog_category.getSelectedItem().toString());
            pst.setString(3, txt_debitBalance.getText());
            pst.setString(4, txt_creditBalance.getText());
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Suceesfully updated db");
            updateTable();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "A/c head already exists");
        }

    }//GEN-LAST:event_dialog_saveActionPerformed

    private void create_acc_headActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_create_acc_headActionPerformed
        setDimention();
        clearFields();

        // TODO add your handling code here:
    }//GEN-LAST:event_create_acc_headActionPerformed
    
    
    public void setDimention(){
        dialog_AccHead.setSize(400, 350);
        final Toolkit toolkit = Toolkit.getDefaultToolkit();
        final Dimension screenSize = toolkit.getScreenSize();
        final int x = (screenSize.width - dialog_AccHead.getWidth()) / 2;
        final int y = (screenSize.height - dialog_AccHead.getHeight()) / 2;
        dialog_AccHead.setLocation(x, y);
        dialog_AccHead.setVisible(true);
        
    }
    private void dialog_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dialog_exitActionPerformed
        // TODO add your handling code here:
        dialog_AccHead.dispose();
        updateTable();
    }//GEN-LAST:event_dialog_exitActionPerformed

    private void exit_itemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exit_itemActionPerformed
        // TODO add your handling code here:
        try{
            conn.close();
            MainMenu m = new MainMenu();
            m.setVisible(true);
            this.dispose();
        }catch(Exception e){
            
        }
    }//GEN-LAST:event_exit_itemActionPerformed

    private void dialog_AccHeadKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dialog_AccHeadKeyPressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_dialog_AccHeadKeyPressed

    private void table_accheadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_accheadMouseClicked
        // TODO add your handling code here:
        showEditDialog();
    }//GEN-LAST:event_table_accheadMouseClicked
    
    private void table_accheadKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_table_accheadKeyPressed
        // TODO add your handling code here:
        try{
            if (KeyEvent.VK_ENTER == evt.getKeyCode()) {
                showEditDialog();
            }
            if (KeyEvent.VK_F2 == evt.getKeyCode()){
                setDimention();
                clearFields();
            }
            if (KeyEvent.VK_F3 == evt.getKeyCode()){
                deleteRecord();
            }
            
        }catch(Exception e){
            
        }
    }//GEN-LAST:event_table_accheadKeyPressed

    private void dialog_modifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dialog_modifyActionPerformed
        // TODO add your handling code here:
        String sql = "update acc_heads set Account_Head=?, Category=?, Debit=?, Credit=? where accID=?";
        try {
            pst = conn.prepareStatement(sql);
            pst.setString(1, txt_accName.getText());
            pst.setString(2, dialog_category.getSelectedItem().toString());
            pst.setString(3, txt_debitBalance.getText());
            pst.setString(4, txt_creditBalance.getText());
            pst.setString(5, accID);
            pst.executeUpdate();
            dialog_AccHead.dispose();
            updateTable();
            JOptionPane.showMessageDialog(null, "Suceesfully updated db");
        } catch (ArrayIndexOutOfBoundsException e){
              JOptionPane.showMessageDialog(null, "Entry does not exist. Please click on \"Create\"");
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_dialog_modifyActionPerformed

    private void txt_accNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_accNameKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ESCAPE ) {
            System.out.println("pressed ESC");
            dialog_AccHead.setVisible(false);
        }
    }//GEN-LAST:event_txt_accNameKeyPressed
    
//the dialog box will display the record details taken from the JTable
    private void showEditDialog(){
        int index = table_acchead.getSelectedRow();
        TableModel model = table_acchead.getModel();
        String acc_name = model.getValueAt(index, 0).toString();
        String category = model.getValueAt(index, 1).toString();
        String debit    = model.getValueAt(index, 2).toString();
        String credit   = model.getValueAt(index, 3).toString();
        
        accID = getID(acc_name);
        System.out.println(accID + acc_name);
        setDimention();
        txt_accName.setText(acc_name);
        dialog_category.setSelectedItem(category);
        txt_creditBalance.setText(credit);
        txt_debitBalance.setText(debit);
        
    }
    
    public String getID(String name){
        String sql = "select accID from acc_heads where Account_Head=?";
        try{
            System.out.println("name="+name);
            pst = conn.prepareStatement(sql);
            pst.setString(1, name);
            System.out.println(sql);
            rs = pst.executeQuery();
            rs.next();
            System.out.println("id="+rs.getString("accID"));
            return rs.getString("accID");
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        return null;
    }
    public void clearFields() {
        txt_accName.setText("");
        txt_creditBalance.setText("0");
        txt_debitBalance.setText("0");
        txt_underTheGroup.setText("");
        dialog_category.setSelectedIndex(4);
    }

    public void deleteRecord(){
        String sql = "delete from acc_heads where accID = ?";
        try{
            int index = table_acchead.getSelectedRow();
            TableModel model = table_acchead.getModel();
            String acc_name = model.getValueAt(index, 0).toString();
            String accID = getID(acc_name);
            System.out.println(accID);
            
            pst = conn.prepareStatement(sql);
            pst.setString(1, accID);
            pst.executeUpdate();
            updateTable();
            JOptionPane.showMessageDialog(null, "Successfully deleted " + acc_name + " record");
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AccountHeads.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AccountHeads.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AccountHeads.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AccountHeads.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AccountHeads().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem create_acc_head;
    private javax.swing.JDialog dialog_AccHead;
    private javax.swing.JComboBox<String> dialog_category;
    private javax.swing.JButton dialog_exit;
    private javax.swing.JButton dialog_modify;
    private javax.swing.JButton dialog_save;
    private javax.swing.JMenuItem exit_item;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table_acchead;
    private javax.swing.JTextField txt_accName;
    private javax.swing.JTextField txt_creditBalance;
    private javax.swing.JTextField txt_debitBalance;
    private javax.swing.JTextField txt_underTheGroup;
    // End of variables declaration//GEN-END:variables
}
