/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package employee.payroll;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.JPanel;
import org.jdesktop.swingx.JXDatePicker;

/**
 *
 * @author chayatan
 */
public class MainMenu extends javax.swing.JFrame {

    /**
     * Creates new form MainMenu
     */
    public MainMenu() {
        initComponents();
        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width/2 - getWidth()/2, size.height/2 - getHeight()/2);
        lbl_emp.setText(String.valueOf(Emp.empID));
        lbl_name.setText(Emp.empName);
        btnGrp_balance.add(radio_monthly);
        btnGrp_balance.add(radio_daily);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dialog_dayBook = new javax.swing.JDialog();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_pNo = new javax.swing.JTextField();
        radio_cashTrans = new javax.swing.JRadioButton();
        dialog_exit = new javax.swing.JButton();
        dialog_preview = new javax.swing.JButton();
        dialog_print = new javax.swing.JButton();
        radio_monthly = new javax.swing.JRadioButton();
        radio_daily = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        datePicker_fdate = new org.jdesktop.swingx.JXDatePicker();
        datePicker_tdate = new org.jdesktop.swingx.JXDatePicker();
        btnGrp_balance = new javax.swing.ButtonGroup();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        lbl_emp = new javax.swing.JLabel();
        lbl_name = new javax.swing.JLabel();
        btn_logout = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenuItem13 = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenuItem14 = new javax.swing.JMenuItem();
        jMenuItem15 = new javax.swing.JMenuItem();
        jMenuItem16 = new javax.swing.JMenuItem();
        jMenuItem17 = new javax.swing.JMenuItem();
        jMenuItem18 = new javax.swing.JMenuItem();
        jMenuItem19 = new javax.swing.JMenuItem();
        jMenuItem20 = new javax.swing.JMenuItem();
        jMenuItem21 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem22 = new javax.swing.JMenuItem();
        jMenuItem23 = new javax.swing.JMenuItem();
        jMenuItem24 = new javax.swing.JMenuItem();
        jMenuItem25 = new javax.swing.JMenuItem();
        jMenuItem26 = new javax.swing.JMenuItem();
        jMenuItem27 = new javax.swing.JMenuItem();
        jMenuItem28 = new javax.swing.JMenuItem();
        jMenuItem29 = new javax.swing.JMenuItem();
        jMenuItem30 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem31 = new javax.swing.JMenuItem();
        jMenuItem32 = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        jMenuItem33 = new javax.swing.JMenuItem();
        jMenuItem34 = new javax.swing.JMenuItem();
        jMenuItem35 = new javax.swing.JMenuItem();
        jMenuItem36 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem37 = new javax.swing.JMenuItem();
        jMenuItem38 = new javax.swing.JMenuItem();
        jMenuItem39 = new javax.swing.JMenuItem();
        jMenuItem40 = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        jMenuItem41 = new javax.swing.JMenuItem();
        jMenuItem42 = new javax.swing.JMenuItem();
        jMenuItem43 = new javax.swing.JMenuItem();
        jMenuItem44 = new javax.swing.JMenuItem();
        jMenuItem45 = new javax.swing.JMenuItem();
        jMenuItem46 = new javax.swing.JMenuItem();
        jMenuItem47 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem48 = new javax.swing.JMenuItem();
        jMenuItem49 = new javax.swing.JMenuItem();
        jMenuItem50 = new javax.swing.JMenuItem();
        jMenuItem51 = new javax.swing.JMenuItem();
        jMenuItem52 = new javax.swing.JMenuItem();
        jMenuItem53 = new javax.swing.JMenuItem();
        jMenuItem54 = new javax.swing.JMenuItem();
        jMenuItem55 = new javax.swing.JMenuItem();
        jMenuItem56 = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        jMenuItem57 = new javax.swing.JMenuItem();
        jMenuItem58 = new javax.swing.JMenuItem();
        jMenuItem59 = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        jMenuItem60 = new javax.swing.JMenuItem();
        jMenuItem61 = new javax.swing.JMenuItem();
        jMenuItem62 = new javax.swing.JMenuItem();
        jMenuItem63 = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        jMenuItem64 = new javax.swing.JMenuItem();
        jMenuItem65 = new javax.swing.JMenuItem();
        jSeparator6 = new javax.swing.JPopupMenu.Separator();
        jMenuItem66 = new javax.swing.JMenuItem();
        jMenuItem67 = new javax.swing.JMenuItem();
        jMenuItem68 = new javax.swing.JMenuItem();
        jMenuItem69 = new javax.swing.JMenuItem();
        jMenuItem70 = new javax.swing.JMenuItem();
        jSeparator7 = new javax.swing.JPopupMenu.Separator();
        jMenuItem71 = new javax.swing.JMenuItem();
        jMenu9 = new javax.swing.JMenu();
        jMenuItem72 = new javax.swing.JMenuItem();
        jSeparator8 = new javax.swing.JPopupMenu.Separator();
        jMenuItem73 = new javax.swing.JMenuItem();
        jMenuItem74 = new javax.swing.JMenuItem();
        jSeparator9 = new javax.swing.JPopupMenu.Separator();
        jMenuItem75 = new javax.swing.JMenuItem();
        jMenuItem76 = new javax.swing.JMenuItem();
        jSeparator10 = new javax.swing.JPopupMenu.Separator();
        jMenuItem77 = new javax.swing.JMenuItem();
        jMenuItem78 = new javax.swing.JMenuItem();
        jMenuItem79 = new javax.swing.JMenuItem();
        jSeparator11 = new javax.swing.JPopupMenu.Separator();
        jMenuItem80 = new javax.swing.JMenuItem();

        dialog_dayBook.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel2.setText("From: ");

        jLabel3.setText("To:");

        jLabel4.setText("Page No starting from:");

        txt_pNo.setText("1");
        txt_pNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_pNoActionPerformed(evt);
            }
        });

        radio_cashTrans.setText("Cash Transaction Only");

        dialog_exit.setText("Exit");
        dialog_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dialog_exitActionPerformed(evt);
            }
        });

        dialog_preview.setText("Preview");

        dialog_print.setText("Print");
        dialog_print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dialog_printActionPerformed(evt);
            }
        });

        radio_monthly.setText("Monthly");

        radio_daily.setText("Daily");
        radio_daily.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_dailyActionPerformed(evt);
            }
        });

        jLabel5.setText("Balance");

        datePicker_fdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                datePicker_fdateActionPerformed(evt);
            }
        });

        datePicker_tdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                datePicker_tdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dialog_dayBookLayout = new javax.swing.GroupLayout(dialog_dayBook.getContentPane());
        dialog_dayBook.getContentPane().setLayout(dialog_dayBookLayout);
        dialog_dayBookLayout.setHorizontalGroup(
            dialog_dayBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialog_dayBookLayout.createSequentialGroup()
                .addGroup(dialog_dayBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dialog_dayBookLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(dialog_dayBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(dialog_dayBookLayout.createSequentialGroup()
                                .addComponent(datePicker_fdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(datePicker_tdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(dialog_exit)
                            .addGroup(dialog_dayBookLayout.createSequentialGroup()
                                .addGap(105, 105, 105)
                                .addComponent(dialog_preview, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36)
                                .addComponent(dialog_print))))
                    .addGroup(dialog_dayBookLayout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addGroup(dialog_dayBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(dialog_dayBookLayout.createSequentialGroup()
                                .addGroup(dialog_dayBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(dialog_dayBookLayout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(radio_monthly)))
                                .addGroup(dialog_dayBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(dialog_dayBookLayout.createSequentialGroup()
                                        .addGap(2, 2, 2)
                                        .addComponent(txt_pNo, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(dialog_dayBookLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(radio_daily))))
                            .addGroup(dialog_dayBookLayout.createSequentialGroup()
                                .addGap(71, 71, 71)
                                .addComponent(radio_cashTrans)))))
                .addGap(0, 40, Short.MAX_VALUE))
        );
        dialog_dayBookLayout.setVerticalGroup(
            dialog_dayBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dialog_dayBookLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(dialog_dayBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(datePicker_fdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(datePicker_tdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(dialog_dayBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txt_pNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(dialog_dayBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radio_monthly)
                    .addComponent(radio_daily)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addComponent(radio_cashTrans)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(dialog_dayBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dialog_exit)
                    .addComponent(dialog_preview)
                    .addComponent(dialog_print))
                .addGap(30, 30, 30))
        );

        jPasswordField1.setText("jPasswordField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Logged in as:");

        lbl_emp.setText("id");

        lbl_name.setText("name");

        btn_logout.setText("Logout");
        btn_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_logoutActionPerformed(evt);
            }
        });

        jMenu1.setText("Entry");

        jMenuItem1.setText("Firm Name");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Setup");
        jMenu1.add(jMenuItem2);
        jMenu1.add(jSeparator1);

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem3.setText("Account Heads");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuItem4.setText("Transaction");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuItem5.setText("Prev - Bal");
        jMenu1.add(jMenuItem5);

        jMenuItem6.setText("Groups");
        jMenu1.add(jMenuItem6);

        jMenuItem7.setText("Exit");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem7);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("DE");

        jMenuItem8.setText("Cheques");
        jMenu2.add(jMenuItem8);

        jMenuItem9.setText("Challans");
        jMenu2.add(jMenuItem9);

        jMenuItem10.setText("Receipts");
        jMenu2.add(jMenuItem10);

        jMenuItem11.setText("Payments");
        jMenu2.add(jMenuItem11);

        jMenuItem12.setText("Journal");
        jMenuItem12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem12ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem12);

        jMenuItem13.setText("Multy Jrnl.");
        jMenu2.add(jMenuItem13);
        jMenu2.add(jSeparator2);

        jMenuItem14.setText("Commodity Name");
        jMenu2.add(jMenuItem14);

        jMenuItem15.setText("Sales");
        jMenu2.add(jMenuItem15);

        jMenuItem16.setText("Sales Return");
        jMenu2.add(jMenuItem16);

        jMenuItem17.setText("Purchase");
        jMenu2.add(jMenuItem17);

        jMenuItem18.setText("Purchase return");
        jMenu2.add(jMenuItem18);

        jMenuItem19.setText("Production");
        jMenu2.add(jMenuItem19);

        jMenuItem20.setText("Consignment Input");
        jMenu2.add(jMenuItem20);

        jMenuItem21.setText("Con.Sales");
        jMenu2.add(jMenuItem21);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Book");

        jMenuItem22.setText("Sales Register");
        jMenu3.add(jMenuItem22);

        jMenuItem23.setText("Sales Retun Register");
        jMenu3.add(jMenuItem23);

        jMenuItem24.setText("Purchase Register");
        jMenu3.add(jMenuItem24);

        jMenuItem25.setText("Purchase Return Register");
        jMenu3.add(jMenuItem25);

        jMenuItem26.setText("Stock Register");
        jMenu3.add(jMenuItem26);

        jMenuItem27.setText("Tax Register");
        jMenu3.add(jMenuItem27);

        jMenuItem28.setText("Misc. Register");
        jMenu3.add(jMenuItem28);

        jMenuItem29.setText("Consignment Stock");
        jMenuItem29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem29ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem29);

        jMenuItem30.setText("Sale Patty");
        jMenu3.add(jMenuItem30);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Report");

        jMenuItem31.setText("Day Book");
        jMenuItem31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem31ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem31);

        jMenuItem32.setText("Ledger");
        jMenu4.add(jMenuItem32);
        jMenu4.add(jSeparator3);

        jMenuItem33.setText("Trial Balance");
        jMenu4.add(jMenuItem33);

        jMenuItem34.setText("Trading Account");
        jMenu4.add(jMenuItem34);

        jMenuItem35.setText("Profit & Loss A/c");
        jMenu4.add(jMenuItem35);

        jMenuItem36.setText("Balance Sheet");
        jMenu4.add(jMenuItem36);

        jMenuBar1.add(jMenu4);

        jMenu5.setText("Schedule");

        jMenuItem37.setText("Sundry Creditors");
        jMenu5.add(jMenuItem37);

        jMenuItem38.setText("Sundry Debitors");
        jMenu5.add(jMenuItem38);

        jMenuItem39.setText("Loan & Advance (Liab)");
        jMenu5.add(jMenuItem39);

        jMenuItem40.setText("Loan & Advance (Asse)");
        jMenu5.add(jMenuItem40);
        jMenu5.add(jSeparator4);

        jMenuItem41.setText("Depreciation Chart ");
        jMenu5.add(jMenuItem41);

        jMenuItem42.setText("Share of Profit/Loss");
        jMenu5.add(jMenuItem42);

        jMenuItem43.setText("Interest Statement");
        jMenu5.add(jMenuItem43);

        jMenuItem44.setText("Statement of Capital");
        jMenu5.add(jMenuItem44);

        jMenuItem45.setText("Statement of Accounts");
        jMenu5.add(jMenuItem45);

        jMenuItem46.setText("Reconciliation Statement");
        jMenu5.add(jMenuItem46);

        jMenuItem47.setText("Statement of Income");
        jMenu5.add(jMenuItem47);

        jMenuBar1.add(jMenu5);

        jMenu6.setText("Input");

        jMenuItem48.setText("Rate of Depreciation");
        jMenu6.add(jMenuItem48);

        jMenuItem49.setText("Interest on Capital");
        jMenu6.add(jMenuItem49);

        jMenuItem50.setText("Interest on Accounts");
        jMenu6.add(jMenuItem50);

        jMenuItem51.setText("Share of Profit");
        jMenu6.add(jMenuItem51);

        jMenuItem52.setText("Reconciliation");
        jMenu6.add(jMenuItem52);

        jMenuItem53.setText("Closing Stock");
        jMenu6.add(jMenuItem53);

        jMenuItem54.setText("Stock Journal");
        jMenu6.add(jMenuItem54);

        jMenuItem55.setText("Multi Stock Journal");
        jMenu6.add(jMenuItem55);

        jMenuItem56.setText("Stock I/O");
        jMenu6.add(jMenuItem56);

        jMenuBar1.add(jMenu6);

        jMenu7.setText("Tax");

        jMenuItem57.setText("Form 3");
        jMenu7.add(jMenuItem57);

        jMenuItem58.setText("Form 4");
        jMenu7.add(jMenuItem58);

        jMenuItem59.setText("Statement of Income");
        jMenu7.add(jMenuItem59);
        jMenu7.add(jSeparator5);

        jMenuItem60.setText("TSP Sales");
        jMenu7.add(jMenuItem60);

        jMenuItem61.setText("TSP Purchase");
        jMenu7.add(jMenuItem61);

        jMenuItem62.setText("Consignment Sales");
        jMenu7.add(jMenuItem62);

        jMenuItem63.setText("Consignment Purchase");
        jMenu7.add(jMenuItem63);

        jMenuBar1.add(jMenu7);

        jMenu8.setText("MIS");

        jMenuItem64.setText("Party Details");
        jMenu8.add(jMenuItem64);

        jMenuItem65.setText("Mail Merge");
        jMenu8.add(jMenuItem65);
        jMenu8.add(jSeparator6);

        jMenuItem66.setText("Average Rate");
        jMenuItem66.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem66ActionPerformed(evt);
            }
        });
        jMenu8.add(jMenuItem66);

        jMenuItem67.setText("Agewise Statement");
        jMenu8.add(jMenuItem67);

        jMenuItem68.setText("Bills Receivable");
        jMenu8.add(jMenuItem68);

        jMenuItem69.setText("Bills Payable");
        jMenu8.add(jMenuItem69);

        jMenuItem70.setText("Overdue Statement");
        jMenu8.add(jMenuItem70);
        jMenu8.add(jSeparator7);

        jMenuItem71.setText("Invoice Design");
        jMenuItem71.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem71ActionPerformed(evt);
            }
        });
        jMenu8.add(jMenuItem71);

        jMenuBar1.add(jMenu8);

        jMenu9.setText("Utility");

        jMenuItem72.setText("Help");
        jMenu9.add(jMenuItem72);
        jMenu9.add(jSeparator8);

        jMenuItem73.setText("Edit file");
        jMenu9.add(jMenuItem73);

        jMenuItem74.setText("Print file");
        jMenu9.add(jMenuItem74);
        jMenu9.add(jSeparator9);

        jMenuItem75.setText("Backup ");
        jMenu9.add(jMenuItem75);

        jMenuItem76.setText("Restore");
        jMenu9.add(jMenuItem76);
        jMenu9.add(jSeparator10);

        jMenuItem77.setText("Calculator");
        jMenu9.add(jMenuItem77);

        jMenuItem78.setText("Diary");
        jMenu9.add(jMenuItem78);

        jMenuItem79.setText("Notepad");
        jMenu9.add(jMenuItem79);
        jMenu9.add(jSeparator11);

        jMenuItem80.setText("Control");
        jMenu9.add(jMenuItem80);

        jMenuBar1.add(jMenu9);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_emp)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_name)
                        .addGap(0, 590, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btn_logout)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_logout)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 421, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lbl_emp)
                    .addComponent(lbl_name))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_logoutActionPerformed
        // TODO add your handling code here:
        login x= new login();
        x.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_logoutActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem12ActionPerformed

    private void jMenuItem29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem29ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem29ActionPerformed

    private void jMenuItem66ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem66ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem66ActionPerformed

    private void jMenuItem71ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem71ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem71ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
            
        AccountHeads A = new AccountHeads();
        A.setVisible(true);
        this.dispose();        // TODO add your handling code here:
        
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        // TODO add your handling code here:
        
        login x= new login();
        x.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        Transaction x= new Transaction();
        x.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem31ActionPerformed
        // TODO add your handling code here:
        System.out.println("wait for the report to get downloaded");
        setDimention();
        
    }//GEN-LAST:event_jMenuItem31ActionPerformed

    public void setDimention(){
        dialog_dayBook.setSize(450, 280);
        final Toolkit toolkit = Toolkit.getDefaultToolkit();
        final Dimension screenSize = toolkit.getScreenSize();
        final int x = (screenSize.width - dialog_dayBook.getWidth()) / 2;
        final int y = (screenSize.height - dialog_dayBook.getHeight()) / 2;
        dialog_dayBook.setLocation(x, y);
        dialog_dayBook.setVisible(true);
    }
    
    private void dialog_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dialog_exitActionPerformed
        // TODO add your handling code here:
        dialog_dayBook.dispose();
        
    }//GEN-LAST:event_dialog_exitActionPerformed

    private void dialog_printActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dialog_printActionPerformed
        // TODO add your handling code here:
        System.out.println("printing..");
        Date fDate = datePicker_fdate.getDate();
        Date tDate = datePicker_tdate.getDate();
        String pNo = txt_pNo.getText();
        System.out.println(fDate);
        boolean bal = radio_monthly.isSelected();
        if (bal){
            System.out.println("bal is monthly");
            
        }
        else{
            System.out.println("bal is daily");
        }
    }//GEN-LAST:event_dialog_printActionPerformed

    private void radio_dailyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_dailyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radio_dailyActionPerformed

    private void datePicker_fdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_datePicker_fdateActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_datePicker_fdateActionPerformed

    private void txt_pNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_pNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_pNoActionPerformed

    private void datePicker_tdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_datePicker_tdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_datePicker_tdateActionPerformed
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btnGrp_balance;
    private javax.swing.JButton btn_logout;
    private org.jdesktop.swingx.JXDatePicker datePicker_fdate;
    private org.jdesktop.swingx.JXDatePicker datePicker_tdate;
    private javax.swing.JDialog dialog_dayBook;
    private javax.swing.JButton dialog_exit;
    private javax.swing.JButton dialog_preview;
    private javax.swing.JButton dialog_print;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem16;
    private javax.swing.JMenuItem jMenuItem17;
    private javax.swing.JMenuItem jMenuItem18;
    private javax.swing.JMenuItem jMenuItem19;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem20;
    private javax.swing.JMenuItem jMenuItem21;
    private javax.swing.JMenuItem jMenuItem22;
    private javax.swing.JMenuItem jMenuItem23;
    private javax.swing.JMenuItem jMenuItem24;
    private javax.swing.JMenuItem jMenuItem25;
    private javax.swing.JMenuItem jMenuItem26;
    private javax.swing.JMenuItem jMenuItem27;
    private javax.swing.JMenuItem jMenuItem28;
    private javax.swing.JMenuItem jMenuItem29;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem30;
    private javax.swing.JMenuItem jMenuItem31;
    private javax.swing.JMenuItem jMenuItem32;
    private javax.swing.JMenuItem jMenuItem33;
    private javax.swing.JMenuItem jMenuItem34;
    private javax.swing.JMenuItem jMenuItem35;
    private javax.swing.JMenuItem jMenuItem36;
    private javax.swing.JMenuItem jMenuItem37;
    private javax.swing.JMenuItem jMenuItem38;
    private javax.swing.JMenuItem jMenuItem39;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem40;
    private javax.swing.JMenuItem jMenuItem41;
    private javax.swing.JMenuItem jMenuItem42;
    private javax.swing.JMenuItem jMenuItem43;
    private javax.swing.JMenuItem jMenuItem44;
    private javax.swing.JMenuItem jMenuItem45;
    private javax.swing.JMenuItem jMenuItem46;
    private javax.swing.JMenuItem jMenuItem47;
    private javax.swing.JMenuItem jMenuItem48;
    private javax.swing.JMenuItem jMenuItem49;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem50;
    private javax.swing.JMenuItem jMenuItem51;
    private javax.swing.JMenuItem jMenuItem52;
    private javax.swing.JMenuItem jMenuItem53;
    private javax.swing.JMenuItem jMenuItem54;
    private javax.swing.JMenuItem jMenuItem55;
    private javax.swing.JMenuItem jMenuItem56;
    private javax.swing.JMenuItem jMenuItem57;
    private javax.swing.JMenuItem jMenuItem58;
    private javax.swing.JMenuItem jMenuItem59;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem60;
    private javax.swing.JMenuItem jMenuItem61;
    private javax.swing.JMenuItem jMenuItem62;
    private javax.swing.JMenuItem jMenuItem63;
    private javax.swing.JMenuItem jMenuItem64;
    private javax.swing.JMenuItem jMenuItem65;
    private javax.swing.JMenuItem jMenuItem66;
    private javax.swing.JMenuItem jMenuItem67;
    private javax.swing.JMenuItem jMenuItem68;
    private javax.swing.JMenuItem jMenuItem69;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem70;
    private javax.swing.JMenuItem jMenuItem71;
    private javax.swing.JMenuItem jMenuItem72;
    private javax.swing.JMenuItem jMenuItem73;
    private javax.swing.JMenuItem jMenuItem74;
    private javax.swing.JMenuItem jMenuItem75;
    private javax.swing.JMenuItem jMenuItem76;
    private javax.swing.JMenuItem jMenuItem77;
    private javax.swing.JMenuItem jMenuItem78;
    private javax.swing.JMenuItem jMenuItem79;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem80;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator10;
    private javax.swing.JPopupMenu.Separator jSeparator11;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JPopupMenu.Separator jSeparator6;
    private javax.swing.JPopupMenu.Separator jSeparator7;
    private javax.swing.JPopupMenu.Separator jSeparator8;
    private javax.swing.JPopupMenu.Separator jSeparator9;
    private javax.swing.JLabel lbl_emp;
    private javax.swing.JLabel lbl_name;
    private javax.swing.JRadioButton radio_cashTrans;
    private javax.swing.JRadioButton radio_daily;
    private javax.swing.JRadioButton radio_monthly;
    private javax.swing.JTextField txt_pNo;
    // End of variables declaration//GEN-END:variables

    
}
